#+TITLE: Knavemacs Emacs Configuration
#+AUTHOR: John Osinski
#+EMAIL: johnosinski80@gmail.com

:  ___  __    ________   ________  ___      ___ _______   _____ ______   ________  ________  ________
: |\  \|\  \ |\   ___  \|\   __  \|\  \    /  /|\  ___ \ |\   _ \  _   \|\   __  \|\   ____\|\   ____\
: \ \  \/  /|\ \  \\ \  \ \  \|\  \ \  \  /  / | \   __/|\ \  \\\__\ \  \ \  \|\  \ \  \___|\ \  \___|
:  \ \   ___  \ \  \\ \  \ \   __  \ \  \/  / / \ \  \_|/_\ \  \\|__| \  \ \   __  \ \  \    \ \_____  \
:   \ \  \\ \  \ \  \\ \  \ \  \ \  \ \    / /   \ \  \_|\ \ \  \    \ \  \ \  \ \  \ \  \____\|____|\  \
:    \ \__\\ \__\ \__\\ \__\ \__\ \__\ \__/ /     \ \_______\ \__\    \ \__\ \__\ \__\ \_______\____\_\  \
:     \|__| \|__|\|__| \|__|\|__|\|__|\|__|/       \|_______|\|__|     \|__|\|__|\|__|\|_______|\_________\
:                                                                                              \|_________|

* What is this?
This is my [[https://www.gnu.org/software/emacs/][GNU Emacs]] configuration setup in an org file. To load this config
in your own emacs instance, you can add the following lines to your ~.emacs~
or ~.config/init.el~ file (the below is assuming that you are putting the emacs
init file and this org file in the ~/.config/emacs folder):

: (require 'org)
: (require 'ob-tangle)
: (org-babel-load-file "~/.config/emacs/config.org")

Throughout my configuration, I may have settings that pertain to either
Windows or Linux since I use this config file across different OS types. If
there are ever any dependencies for either platform, they can be looked up
by searching for ~;; DEP:~ in this file.

Credit should be given where credit is due. Much of this config is heavily
inspired (and sometimes copied verbatim) from System Crafter's *Emacs From Scratch*
series on youtube. Definitely a must watch.

* Full Emacs Configuration
The following sections both describe and provide the elisp used to configure
various aspects of my emacs instance.

** Basic Configuration
*** Garbage Collection
I've read a lot about different ways to approach this. I'm going off a stack exchange
post that [[https://emacs.stackexchange.com/question/34342/is-there-any-downside-to-setting-gc-cons-threshold-very-high-and-collecting-ga][you can read here]] with some suggestions on how to set this. I'm using a
single command for now and we'll see how that goes.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold (* 1024 1024 100)) ;; about 100MB
#+END_SRC

*** Basic Visual Changes
Vanilla, unconfigured emacs starts with a tool bar, scroll bar, menus, and
other visual elements at play that I disable right from the get-go.

#+BEGIN_SRC emacs-lisp 
  ;; setting some default settings to start with a minimal Emacs startup
  (setq inhibit-startup-message t) ;; no more start up message
  (setq visible-bell t)            ;; stop beeping
  (scroll-bar-mode -1)             ;; disable scroll bars
  (tool-bar-mode -1)               ;; disable tool bar
  (tooltip-mode -1)                ;; disable tooltips
  (set-fringe-mode 10)             ;; sets fringe size
  (menu-bar-mode -1)               ;; disable menu bar
#+END_SRC

*** Enable Line Numbers
I like to use line numbers on the left-hand side, and like to have relative
line numbers shown so I know how far apart various lines are from my current
cursor location.

#+BEGIN_SRC emacs-lisp
  ;; update the UI with additional basic settings
  (setq display-line-numbers-type 'relative); enable relative line numbers
  (column-number-mode)                 ; show column number in mode line
  (global-display-line-numbers-mode t) ; enable line numbers globally
  (dolist (mode '(term-mode-hook        ; define modes that we don't want to see line numbers on
		eshell-mode-hook
    dired-sidebar-mode-hook
		which-key-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+END_SRC

*** Font Configuration
On my linux workspace, I like to set the font to my linking. Note that this
assumes the font is already present on the workspace.

#+BEGIN_SRC emacs-lisp
  ;; set default font settings for my favorite linux font if not on windows
  ;; DEP: requires "Inconsolata Nerd Font" installed on linux and "Hermit" installed on windows.
  (if (not(eq system-type 'windows-nt ))
      (set-face-attribute `default nil :font "Inconsolata Nerd Font" :height 120))
  (if (eq system-type 'windows-nt) (set-face-attribute `default nil :font "Hermit" :height 120))
#+END_SRC

*** Backup File Rules
It is worth nothing that the emacs manual has a good description of backups by
copying vs renaming. Right now I am using the other mode (copy on backing up),
so that I don't start causing issues with system links, I might need to change to
the other method if it's too slow. In any case, I define a specific directory
for my backup files.

#+BEGIN_SRC emacs-lisp
  ;; set a default location for backup files, instead of the files being created
  ;; right next to the original sources
  (if (not (file-exists-p "~/.local/share/emacs-saves"))
      (make-directory "~/.local/share/emacs-saves" t))
  (setq backup-directory-alist '(("." . "~/.local/share/emacs-saves")))
  (setq make-backup-files t
	backup-by-copying t
	version-control t
	delete-old-version t
	delete-by-moving-to-trash t
	kept-old-versions 6
	kept-new-versions 6
	auto-save-default t
	auto-save-timeout 20
	auto-save-interval 200
	)
#+END_SRC

** Package Management and Setup
*** Initialize Package Sources
I use the following three sources for downloadable emacs packages:
 - elpa, the GNU ELPA package archive
 - melpa, the "big one"
 - org, to get the latest version of org-mode functionality

#+BEGIN_SRC emacs-lisp
  ;; initialize package sources
  (require 'package)
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
#+END_SRC

*** Setup of use-package
I use use-package as my main package manager for downloading and configuring
external emacs packages. I set use-package-always-ensure because I want all
packages defined in this config file to be installed automatically if not
already present on my system.

#+BEGIN_SRC emacs-lisp
  ;; SETUP: use-package
  ;; PURPOSE: for easy installation of other packages
  ;; initialize use-package on non-linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t)
#+END_SRC

** Completion, Hints, Help Framework
*** Ivy
I use the Ivy ecosystem for my general completion mechanism in Emacs. Other
completion engines to exist, like helm. Just a tip for Ivy, I can use
~M-o~ while in an Ivy list can provide some additonal functions on list entries!

#+BEGIN_SRC emacs-lisp
  ;; SETUP: ivy
  ;; PURPOSE: completion framework for emacs
  (use-package ivy
    :diminish ;; keep out of mode line
    :bind (("C-s" . swiper)
	 :map ivy-minibuffer-map
	 ("TAB" . ivy-alt-done)
	 ("C-l" . ivy-alt-done)
	 ("C-j" . ivy-next-line)
	 ("C-k" . ivy-previous-line)
	 :map ivy-switch-buffer-map
	 ("C-k" . ivy-previous-line)
	 ("C-l" . ivy-done)
	 ("C-d" . ivy-switch-buffer-kill)
	 :map ivy-reverse-i-search-map
	 ("C-k" . ivy-previous-line)
	 ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))
#+END_SRC

*** Counsel
#+BEGIN_SRC emacs-lisp
  ;; SETUP: counsel
  ;; PURPOSE: provide versions of common emacs commands using Ivy
  (use-package counsel
    :diminish
    :config
    (counsel-mode 1))
#+END_SRC

*** Which-key
#+BEGIN_SRC emacs-lisp
  ;; SETUP: which-key
  ;; PURPOSE: provides assistance in showing what key permutations/options exist while entering commands
  (use-package which-key
    :init (which-key-mode)
    :diminish
    :config
    (setq which-key-idle-delay 0.9))
#+END_SRC

*** Ivy-rich
#+BEGIN_SRC emacs-lisp
  ;; SETUP: ivy-rich
  ;; PURPOSE: provides assistance in showing details for commands and completions from ivy and counsel
  (use-package ivy-rich
    :init (ivy-rich-mode 1))
#+END_SRC

*** Helpful
#+BEGIN_SRC emacs-lisp
  ;; SETUP: helpful
  ;; PURPOSE: provides alternative, deep detail ontop of the existing help documentation in emacs
  (use-package helpful
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+END_SRC

** File Management Configuration
*** Dired
Some modifications to dired to support my usage of the functionality
#+BEGIN_SRC emacs-lisp
  (defun knavemacs/dired-mode-setup ()
    (dired-hide-details-mode))

  (use-package dired
    :hook (dired-mode . knavemacs/dired-mode-setup)
    :ensure nil
    :commands (dired dired-jump)
    :custom ((dired-listing-switches "-alGh --group-directories-first"))
    )
#+END_SRC

*** Dired-Single
Prevents a bunch of dired buffers from accumulating in the buffer list
#+BEGIN_SRC emacs-lisp
  ;; SETUP: dired-single
  ;; PURPOSE: prevents a bunch of dired buffers from accumulating in the buffer list
  (use-package dired-single)
#+END_SRC

*** Dired-Hide-Dotfiles
The name says it all.
#+BEGIN_SRC emacs-lisp
  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode))
#+END_SRC

*** Dired-Subtree
The name says it all.
#+BEGIN_SRC emacs-lisp
  (use-package dired-subtree)
#+END_SRC

** Org-Mode Configuration
*** Org (general config)
#+BEGIN_SRC emacs-lisp
  ;; PURPOSE: this manages my getting things done workflow during work
  (defun knavemacs/org-mode-setup ()
    (org-indent-mode))

  (use-package org
    :hook (org-mode . knavemacs/org-mode-setup)
    :config
    (setf (cdr (rassoc 'find-file-other-window org-link-frame-setup)) 'find-file) ; open links in same buffer
    (setq org-ellipsis " ▾"
	  ;org-hide-emphasis-markers t
    )
    (setq org-agenda-files (list "~/.org"))
    (setq org-refile-targets
	  '((nil :maxlevel . 1)
	    (org-agenda-files :maxlevel . 2)))
    (setq org-todo-keywords
	  '((sequence "TASK(k)" "TODO(t)" "NEXT(x)" "WAIT(w@/!)" "GAVE(v@/!)" "MEET(m@/!)" "|" "DONE(d!)" "CANCELED(c)")
	    (sequence "NOTICE(n)" "|" "RESOLVED(r@)")
	    ))
    (setq org-todo-keywoard-faces
	  '(("TODO" . org-warning) ("NEXT" . "green") ("WAIT" . "yellow") ("GAVE" . "orange") ("MEET" . "yellow")
	    ("DONE" . "blue") ("CANCELED" . "purple")))

    ;; custom agenda views
    (setq org-agenda-custom-commands
	  '(("d" "Work-Week Dashboard"
	     (
	      (todo "NOTICE" ((org-agenda-overriding-header "Notices for Today")))
	      (agenda "" ((org-deadline-warning-days 7)))
	      (todo "TASK" ((org-agenda-overriding-header "Additional Tasks Today")))
	      (tags-todo "+unfiled" ((org-agenda-overriding-header "Unfiled TODOs")))
	      (todo "WAIT"
		    ((org-agenda-overriding-header "Waiting on Confirmation")))
	      (todo "GAVE"
		    ((org-agenda-overriding-header "TODOs Delegated to Someone Else")))))))

    ;; capture templates
    (setq org-capture-templates
	  '(
	    ("n" "Post Notice" entry (file+olp "~/.org/notice.org" "Notice")
	     "* NOTICE %?\n%U Notice Created" :empty-lines 1)

	    ("k" "New Task Today" entry (file+olp "~/.org/unfiled.org" "Tasks")
	     "* TASK %?\n %i" :empty-lines 1)
	    
	    ("t" "New Todo" entry (file+olp "~/.org/unfiled.org" "Todos")
	     "* TODO %? :unfiled:\n %i" :empty-lines 1)

	    ("m" "Meeting Notes" entry (file+olp "~/.org/unfiled.org" "Meetings")
	     "* %t %? :unfiled:\n %i" :empty-lines 1)

	    ("w" "Start Work Cycle" entry (file+olp+datetree "~/.org/worklog.org" "Work Log")
  	     "* %? :WorkNew:\n%U Work Cycle Created\n%i" :empty-lines 1)
	    ))
    )
#+END_SRC

*** Org Bullets
#+BEGIN_SRC emacs-lisp
  ;; SETUP: org-bullets
  ;; PURPOSE: nicer bullets when working in org files
  (use-package org-bullets
    :after org
    :hook (org-mode . org-bullets-mode))
#+END_SRC

*** Pretty Hyphens
This is done to transform dash hyphens into dots.
#+BEGIN_SRC emacs-lisp
  ;; make hyphens dots
  ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
			    '(("^ *\\([-]\\) "
			       (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
#+END_SRC

** Note-Taking Configuration
*** Markdown Mode
I specify Markdown mode here, because I usually use markdown to take notes
#+BEGIN_SRC emacs-lisp
  ;; SETUP: markdown-mode
  ;; PURPOSE: to provide emacs facilities to edit and create md files
  (use-package markdown-mode)
#+END_SRC

*** Denote
Using denote for note taking and knowledge management
#+BEGIN_SRC emacs-lisp
  ;; SETUP: denote
  ;; PURPOSE: provides facilities for note taking and knowledge management
  (use-package denote
    :init
    (add-hook 'find-file-hook #'denote-link-buttonize-buffer)
    :config
    (setq denote-directory (expand-file-name "~/Documents/denote"))
    (setq denote-prompts '(subdirectory title keywords))
    (setq denote-known-keywords '("info" "idea" "meta" "index" "refined"))
    (setq denote-file-type "markdown-yaml")

    (defun denote-subdirectory-with-type ()
      "Create a note of a specific type, in a specific subdirectory"
      (declare (interactive-only t))
      (interactive)
      (let ((denote-prompts '(file-type subdirectory title keywords)))
        (call-interactively #'denote)))

    (defun denote-journal-entry ()
      "Create an entry tagged 'journal' with the date as its title.
      If a journal for the current day exists, visit it.  If multiple
      entries exist, prompt with completion for a choice between them.
      Else create a new file."
      (interactive)
      (let* ((today (format-time-string "%A %e %B %Y"))
        (string (denote-sluggify today))
        (files (denote-directory-files-matching-regexp string)))
      (cond
        ((> (length files) 1)
        (find-file (completing-read "Select file: " files nil :require-match)))
      (files
        (find-file (car files)))
      (t
        (denote
          today
          '("journal")
          'org
          "~/Documents/denote/journal")))))
    )
#+END_SRC

** Visual Theme and Aesthetic
*** all-the-icons
#+BEGIN_SRC emacs-lisp
  ;; SETUP: all-the-icons
  ;; PURPOSE: provide nerdfont-like icons for graphical elements (like doom-modeline)
  ;; DEP: must run all-the-icons-install-fonts to install the fonts to the local system.
  ;;       on Windows, double-click each downloaded font file and click install.
  ;;       The below use-package form should automatically 
  (use-package all-the-icons
    :if (display-graphic-p)
    :commands all-the-icons-install-fonts
    :init
    (unless (find-font (font-spec :name "all-the-icons"))
      (all-the-icons-install-fonts t)))
#+END_SRC

*** all-the-icons-dired
#+BEGIN_SRC emacs-lisp
  ;; SETUP: all-the-icons-dired
  ;; PURPOSE: provides nerdfont-like icons specifically for dired buffers
  (use-package all-the-icons-dired
    :if (display-graphic-p)
    :hook (dired-mode . all-the-icons-dired-mode))
#+END_SRC

*** Doom Theme(s)
#+BEGIN_SRC emacs-lisp
  ;; SETUP: doom-themes
  ;; PURPOSE: provide newer aesthetic themes outside the normal emacs defaults
  (use-package doom-themes
    :config
    (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
	  doom-themes-enable-italic t) ; if nil, italic is universally disabled
    (if (not(eq system-type 'windows-nt )) (load-theme 'doom-badger t))
    (if (eq system-type 'windows-nt) (load-theme 'doom-opera-light t)))
#+END_SRC

*** Doom Modeline
#+BEGIN_SRC emacs-lisp
  ;; SETUP: doom-modeline
  ;; PURPOSE: provide an aesthetic, minimal mode line for emacs
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    ;; :custom ((doom-modeline-height 15))
    )
#+END_SRC

*** Rainbow Delimiters
#+BEGIN_SRC emacs-lisp
  ;; SETUP: rainbow-delimiters
  ;; PURPOSE: make apparent the nested parenthesis in program code like Elisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+END_SRC

*** Rainbow Mode
#+BEGIN_SRC emacs-lisp
  ;; SETUP: rainbow-mode
  ;; PURPOSE: provide color highlighting for rgb/hex codes in the buffer
  (use-package rainbow-mode)
#+END_SRC

** Project and Version Control
*** Projectile
A nice thing about projectile is I can set directory (project) specific variables, including what
command runs when I "run" the project. Note that having ripgrep installed makes seach pretty
excellent across project files.

#+BEGIN_SRC emacs-lisp
  ;; SETUP: projectile
  ;; PURPOSE: project discrovey system and framework for emacs
  ;; DEP: having ripgrep installed will allow me to search better in projects
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :init
    (when (file-directory-p "~/Projects")
      (setq projectile-project-search-path '("~/Projects")))
    )

  ;; SETUP: counsel-projectile
  ;; PURPOSE: counsel UI and further IVY integration to projectile
  (use-package counsel-projectile
    :config (counsel-projectile-mode))
#+END_SRC

*** Magit
#+BEGIN_SRC emacs-lisp
  ;; SETUP: magit
  ;; PURPOSE: git interface with emacs
  ;; DEP: I need to set the path manually to git for windows
  (use-package magit
    :init
    (if (eq system-type 'windows-nt) (setq exec-path (append exec-path '("C:/Users/josinski/auxiliary/other/lsys/cmder/vendor/git-for-windows/bin"))))
    )
#+END_SRC

** Custom Functions
*** Navigation Functions
*forward-or-backward-sexp*
Grabbed from the Emacs Wiki, here is a custom function that 'smartly' emulates
the '%' key from vi, to allow jumping between matching parenthesis (or sexp).

#+BEGIN_SRC emacs-lisp
  (defun forward-or-backward-sexp (&optional arg)
  "Go to the matching parenthesis character if one is adjacent to point."
  (interactive "^p")
  (cond ((looking-at "\\s(") (forward-sexp arg))
        ((looking-back "\\s)" 1) (backward-sexp arg))
        ;; Now, try to succeed from inside of a bracket
        ((looking-at "\\s)") (forward-char) (backward-sexp arg))
        ((looking-back "\\s(" 1) (backward-char) (forward-sexp arg))))
#+END_SRC

*** Date Functions
*org-quick-time-stamp-inactive*
Provides a single function that can be mapped to a key, as a shortcut to insert
an inactive timestamp of the current time without user prompt.

#+BEGIN_SRC emacs-lisp
  (defun org-quick-time-stamp-inactive ()
  "Insert an inactive time stamp of the current time without user prompt"
  (interactive)
  (let ((current-prefix-arg '(16)))
    (call-interactively 'org-time-stamp-inactive)))
#+END_SRC

** Key-Bind Modifications
*** Meow
I use [[https://github.com/meow-edit/meow][meow]] as my modal editing system, and it is amazing!
I use ~<~ and ~>~ to navigate up and down screenfulls of text,
as well as ~N~ and ~M~ to go to the true beginning / end of a line. I can use
~SPC-?~ to get a good cheatsheet of what meow keys exist. I can always use
~C-h k~ as well to check a specific key, or launch ~meow-tutor~ for a refresher.
Take a look below, because I also change the purpose of the digit keys and add
a few more functions when pressing the leader key!
#+BEGIN_SRC emacs-lisp
  ;; SETUP: meow
  ;; PURPOSE: more native modal editing mode for Emacs
  (use-package meow
    :diminish
    :config
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("<escape>" . ignore))
    (meow-leader-define-key
     ;; SPC j/k will run the original command in MOTION state.
     '("j" . "H-j")
     '("k" . "H-k")
     ;; Use SPC (0-9) for digit arguments.
     '("1" . tab-bar-close-tab)
     '("2" . tab-bar-new-tab)
     '("3" . switch-to-buffer-other-tab)
     ;'("4" . meow-digit-argument)
     '("5" . forward-or-backward-sexp)
     ;'("6" . meow-digit-argument)
     ;'("7" . meow-digit-argument)
     '("b" . ivy-switch-buffer)
     '("9" . tab-bar-switch-to-prev-tab)
     '("0" . tab-bar-switch-to-next-tab)
     '("k" . kill-this-buffer)
     '("f" . org-open-at-point)
     '("t" . dired-sidebar-toggle-sidebar)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))
    (meow-normal-define-key
     '("C-0" . meow-expand-0)
     '("C-9" . meow-expand-9)
     '("C-8" . meow-expand-8)
     '("C-7" . meow-expand-7)
     '("C-6" . meow-expand-6)
     '("C-5" . meow-expand-5)
     '("C-4" . meow-expand-4)
     '("C-3" . meow-expand-3)
     '("C-2" . meow-expand-2)
     '("C-1" . meow-expand-1)
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("S" . markdown-toggle-markup-hiding)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . hydra-shift-viewport/body)
     '("Z" . hydra-save-andor-close/body)
     '("'" . repeat)
     '("<escape>" . ignore)
     ;; deviating from the suggested map to allow easy scrolling of screens
     ;; as well as getting to true beginning / ends of lines
     '("<" . scroll-down-command)
     '(">" . scroll-up-command)
     '("N" . move-beginning-of-line)
     '("M" . move-end-of-line)
     ))

  (meow-setup)
  (meow-global-mode 1)
    )
#+END_SRC

*** Hydra
#+BEGIN_SRC emacs-lisp
  ;; SETUP: hydra
  ;; PURPOSE: tie related/successive commands together to provide family modes of key bindings
  (use-package hydra)
  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))
  (defhydra hydra-window-resize (:timeout 4)
    "resize split windows"
    ("j" enlarge-window "inc-height")
    ("k" shrink-window "dec-height")
    ("h" shrink-window-horizontally "dec-width")
    ("l" enlarge-window-horizontally "inc-width")
    ("f" nil "finished" :ext t))
  (defhydra hydra-shift-viewport (:timeout 4)
    "shift view around, or pop, selection"
    ("z" recenter "recenter" :exit t)
    ("t" (recenter-top-bottom 0) "shift to top" :exit t)
    ("b" (recenter-top-bottom -1) "shift to bottom" :exit t)
    ("g" meow-pop-selection "Pop Selection")
    ("f" nil "finished" :ext t))
  (defhydra hydra-save-andor-close (:timeout 4)
    "Quick kill emacs, optionally save all"
    ("Z" (save-buffers-kill-terminal) "Save Close All")
    ("Q" (kill-emacs) "Kill Emacs")
    ("f" nil "cancel" :ext t))
#+END_SRC

*** General
I use general to setup some additional keybinds based on a global leader. Like my own keypad versus
the space key used for meow.
#+BEGIN_SRC emacs-lisp
  ;; SETUP: general
  ;; PURPOSE: provide convenient and consistent keymap definitions, including with leader keys
  (use-package general
    :config
    ;; General global key remaps
    (general-define-key
     "C-x C-b" 'ibuffer) ; remap buffer list to interactive list 

    ;; Personal prompt keys
    (general-create-definer knavemacs/leader-keys
			    :keymaps 'global
			    :prefix "C-c p")
    (knavemacs/leader-keys
     "p"  '(projectile-command-map :which-key "projectile")
     "g"  '(magit-status :which-key "git status")

     "n"  '(:ignore t :which-key "denote")
     "nn" '(denote :which-key "Create Note")
     "nN" '(denote-subdirectory-with-type :whick-key "Create Specific Note Type")
     "ni" '(denote-link :which-key "Create Note Link")
     "nI" '(denote-link-add-links :which-key "Create Multiple Links")
     "nb" '(denote-link-backlinks :which-key "Show Backlinks")
     "nl" '(denote-link-after-creating :which-key "Create & Link New Note")
     "nr" '(denote-rename-file :which-key "Rename File")
     "nR" '(denote-rename-file-using-front-matter :which-key "Rename Per Front Matter")
     "nj" '(denote-journal-entry :which-key "Create Journal Entry")

     "o"  '(:ignore t :which-key "org-mode")
     "oa" '(org-agenda :which-key "org-agenda")
     "oc" '(org-capture :which-key "org-capture")
     "ol" '(org-store-link :which-key "org-store-link")
     "od" '(org-quick-time-stamp-inactive :which-key "inactive timestamp")

     "s"  '(:ignore t :which-key "scale/size")
     "st" '(hydra-text-scale/body :which-key "scale text")
     "sw" '(hydra-window-resize/body :which-key "resize window"))
     
    ;; non-leader key defininitions (mainly for window management)
    (general-define-key
     :prefix "C-c w"

     "h" '(windmove-left :whick-key "Move-to Left Pane")
     "l" '(windmove-right :which-key "Move-to Right Pane")
     "j" '(windmove-down :which-key "Move-to Down Pane")
     "k" '(windmove-up :which-key "Move-to Up Pane")
     "s" '(hydra-window-resize/body :which-key "resize window"))

    ;; dired configurations
    ;; note, <space>-j to jump (dired-goto-file) in dired buffers
    ;; note, <space>-j to open current buffer location in dired for other buffers
    ;; note, o to open file in a different buffer split for editing (vs Enter)
    ;; note, C-o to open file in a differnet buffer split, keep focus on dired
    (general-define-key
     :keymaps 'dired-mode-map
     "h" 'dired-single-up-directory
     "l" 'dired-single-buffer
     "K" 'dired-do-kill-lines
     "H" 'dired-hide-dotfiles-mode
     ";" 'dired-subtree-toggle
     )

     )
#+END_SRC

