#+TITLE: Knavemacs Emacs Configuration
#+AUTHOR: John Osinski
#+EMAIL: johnosinski80@gmail.com

:  ___  __    ________   ________  ___      ___ _______   _____ ______   ________  ________  ________
: |\  \|\  \ |\   ___  \|\   __  \|\  \    /  /|\  ___ \ |\   _ \  _   \|\   __  \|\   ____\|\   ____\
: \ \  \/  /|\ \  \\ \  \ \  \|\  \ \  \  /  / | \   __/|\ \  \\\__\ \  \ \  \|\  \ \  \___|\ \  \___|
:  \ \   ___  \ \  \\ \  \ \   __  \ \  \/  / / \ \  \_|/_\ \  \\|__| \  \ \   __  \ \  \    \ \_____  \
:   \ \  \\ \  \ \  \\ \  \ \  \ \  \ \    / /   \ \  \_|\ \ \  \    \ \  \ \  \ \  \ \  \____\|____|\  \
:    \ \__\\ \__\ \__\\ \__\ \__\ \__\ \__/ /     \ \_______\ \__\    \ \__\ \__\ \__\ \_______\____\_\  \
:     \|__| \|__|\|__| \|__|\|__|\|__|\|__|/       \|_______|\|__|     \|__|\|__|\|__|\|_______|\_________\
:                                                                                              \|_________|

* What is this?
This is my [[https://www.gnu.org/software/emacs/][GNU Emacs]] configuration setup in an org file. To load this config
in your own emacs instance, you can add the following lines to your ~.emacs~
or ~.config/init.el~ file (the below is assuming that you are putting the emacs
init file and this org file in the ~/.config/emacs folder):

: (require 'org)
: (require 'ob-tangle)
: (org-babel-load-file "~/.config/emacs/config.org")

Throughout my configuration, I may have settings that pertain to either
Windows or Linux since I use this config file across different OS types. If
there are ever any dependencies for either platform, they can be looked up
by searching for ~;; DEP:~ in this file.

Credit should be given where credit is due. Much of this config is heavily
inspired (and sometimes copied verbatim) from System Crafter's *Emacs From Scratch*
series on youtube. Definitely a must watch.

You can see my full Emacs configuration by going to my [[/config.org][config.org]] file.
